👣1.0:  Crear deb para debian y termux

diff --git a/.github/workflows/gradle_build.yml b/.github/workflows/gradle_build.yml
--- a/.github/workflows/gradle_build.yml
+++ b/.github/workflows/gradle_build.yml
@@ -76,7 +76,56 @@ jobs:
           #
           cat > deb-package-termux/data/data/com.termux/files/usr/bin/apkeditor <<EOL
           #!/data/data/com.termux/files/usr/bin/bash
-          java -jar /data/com.termux/files/usr/share/apkeditor/apkeditor.jar 
+          
+          prog="$0"
+          while [ -h "${prog}" ]; do
+              newProg=$(/data/data/com.termux/files/usr/bin/ls -ld "${prog}"
+              newProg=$(expr "${newProg}" : ".* -> \(.*\)$")
+              if expr "x${newProg}" : 'x/' >/dev/null; then
+                  prog="${newProg}" 
+              else
+                  progdir=$(dirname "${prog}")
+                  prog="${progdir}/${newProg}"
+              fi
+          done
+          oldwd=$(pwd)
+          progdir=$(dirname "${prog}")
+          cd "${progdir}"
+          progdir=$(pwd)
+          prog="${progdir}"/$(basename "${prog}")
+          cd "${oldwd}"
+
+          jarfile=apkeditor.jar
+          libdir="$PREFIX/share/apkeditor"
+          if [ ! -r "$libdir/$jarfile" ]; then
+             echo $(basename "$prog")": can't find $jarfile"
+             exit 1
+          fi
+
+          javaOpts="-Xmx512M -Dfile.encoding=utf-8"
+
+          while expr "x$1" : 'x-J' >/dev/null; do
+                opt=$(expr "$1" : '-J\(.*\)')
+                javaOpts="${javaOpts} -${opt}"
+                shift
+          done
+
+          if [ "$OSTYPE" = "cygwin" ]; then
+               jarpath=$(cygpath -w "$libdir/$jarfile")
+          else
+               jarpath="$libdir/$jarfile"
+          fi
+
+          PATH=$PATH:$(pwd)
+          export PATH
+
+          if [ -f "$1" ]; then
+             input_file="$1"
+                output_file="${input_file%.*}.apk"
+                exec java $javaOpts -jar "$jarpath" m -i "$input_file" -o "$output_file"
+          else
+                exec java $javaOpts -jar "$jarpath" "$@"
+          fi
           EOL
           
           
@@ -122,7 +171,7 @@ jobs:
       - name: Upload APKEDITOR.jar 
         uses: actions/upload-artifact@v4
         with:
-          name: APKEDITOR.jar  
+          name: APKEDITOR  
           path: build/libs  
 
     
